Text_2=Parentesi di apertura non corrispondente dopo la posizione 
Text_3=Parentesi di chiusura non corrispondente prima della posizione 
Text_4=Parentesi di apertura non corrispondente dopo la posizione 
Text_5=Tag di apertura duplicato [
Text_6=:] nella posizione 
Text_7=Tag di chiusura non corrispondente [:
Text_8=] nella posizione 
Text_9=Tag di apertura non corrispondente [
Text_10=:] nella posizione 

Text_11=Nessun padre registrato
Text_12=Nessuna madre registrata

Text_20=(Principale)
Text_21=\ Nessun nome registrato

Text_52=\ Nome del progetto
Text_53=\ Nome del file
Text_54=\ Server locale/remoto
Text_55=\ Locale
Text_56=\ Nome del progetto
Text_57=\ Nome del file
Text_58=\ Server
Text_67=\ Progetto chiuso
Text_68=\ Tempo ora
Text_71=\ Nome del progetto
Text_73=\ Nome del file
Text_75=\ Nome della cartella
Text_77=\ Nome del server
Text_79=\ Ultima chiuso
Text_81=\ Ultimo backup
Text_83=\ Tipo di database
Text_85=\ Database ver:
Text_91=Errore di scrittura del file di registro utente: \n
Text_92=Il file di registro richiesto non esiste
Text_93=Errore di lettura del file di registro utente: \n
Text_94=Messaggio di errore del registro
Text_96=Errore di scrittura dell'utente AUXfile: \n
Text_97=file ausiliario utente non valido - file cancellato
Text_98=File ausiliario utente Userid non valido - File cancellato
Text_99=Errore di lettura del file AUX dell'utente: \n
Text_100=Messaggio di errore AUX utente
Text_102=\ HRE TCP Server è iniziato su \n
Text_103=\ HRE TCP Server Modalità interrotta
Text_104=Stato del server HRE

Text_110=Numero di persone
Text_111=Numero di nomi
Text_112=Numero di eventi
Text_113=Numero di luoghi
Text_114=Numero di fonti
Text_115=Numero di citazioni
Text_116=Numero di elementi della fonte
Text_117=Numero di tipi di evento
Text_118=Numero di repository
Text_119=Numero di file multimediali